### ISSUE TITLE
LocalStorage is not defined

### ISSUE THREAD

**Issue by sumit-kr-das** [anil-sidhu/next-rtk#1]
- error src\app\redux\slice.js (5:22) @ localStorage
- error ReferenceError: localStorage is not defined
    at eval (./src/app/redux/slice.js:11:23)
    at (ssr)/./src/app/redux/slice.js (E:\Downloads\next-rtk-main\next-rtk-main\.next\server\app\page.js:1271:1)
    at __webpack_require__ (E:\Downloads\next-rtk-main\next-rtk-main\.next\server\webpack-runtime.js:33:43)
    at eval (./src/app/redux/store.js:5:64)
    at (ssr)/./src/app/redux/store.js (E:\Downloads\next-rtk-main\next-rtk-main\.next\server\app\page.js:1282:1)
    at __webpack_require__ (E:\Downloads\next-rtk-main\next-rtk-main\.next\server\webpack-runtime.js:33:43)
    at eval (./src/app/redux/providers.js:7:64)
    at (ssr)/./src/app/redux/providers.js (E:\Downloads\next-rtk-main\next-rtk-main\.next\server\app\page.js:1260:1)
    at __webpack_require__ (E:\Downloads\next-rtk-main\next-rtk-main\.next\server\webpack-runtime.js:33:43)
  3 | const initialState = {
  4 |     userAPIData: [],
> 5 |     users: JSON.parse(localStorage.getItem("users")) ? JSON.parse(localStorage.getItem("users")) : []
    |                      ^
  6 | }

**Comment by sumit-kr-das** [comment]
```js
   const initialState = {
    userAPIData: [],
    users: JSON.parse(localStorage.getItem("users")) ? JSON.parse(localStorage.getItem("users")) : []
    }
```
The error I'm encountering (ReferenceError: localStorage is not defined) suggests that the localStorage object is not available in the current environment. This issue typically occurs when running code that involves the browser's localStorage object on the server side during server-side rendering (SSR).

```js
const isServer = typeof window === 'undefined';

let isExist = null;

if (!isServer) {
  isExist = JSON.parse(localStorage.getItem("user") || "{}") || null;
}

```
This code also is not working may be in the time of serverside rendering window is not available. so it throw us-
Unhandled Runtime Error
Error: Hydration failed because the initial UI does not match what was rendered on the server.
